### ISSUE TITLE
updateUser > Getting "Invalid input ';': expected whitespace, UNIQUE or a pattern" error when updating with the existing user role

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1221]
**Describe the bug**
updateUser  > Getting `Invalid input ';': expected whitespace, UNIQUE or a pattern` error when updating with the existing user role

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Proper validation message should be returned when updating with the existing user role

**Actual Result**
Getting `Invalid input ';': expected whitespace, UNIQUE or a pattern` error when updating with the existing user role
See video -  https://drive.google.com/file/d/1sWgm5w5NZW_eD9VZB2WJ0F04Pe8x28na/view?usp=sharing

**GraphQL Query(updateUser):**
![image](https://user-images.githubusercontent.com/5212585/93332070-e01ed800-f83e-11ea-917a-fa27f438fc8a.png)

**GraphQL response**
```

    "data": {
        "updateUser": {
            "user": {
                "id": "2nVxthkjz",
                "fullName": "FirstName1692020045801 LastName1692020045801",
                "firstName": "FirstName1692020045801",
                "avatarLetters": "FL",
                "createdAt": "2020-09-16T10:30:55.702+05:30",
                "email": {
                    "canRead": true,
                    "canEdit": true,
                    "value": "piyush123456@mail.com"
                },
                "realFirstName": {
                    "canRead": true,
                    "canEdit": true,
                    "value": "FirstName1692020045801"
                },
                "realLastName": {
                    "canRead": true,
                    "canEdit": true,
                    "value": "LastName1692020045801"
                },
                "displayFirstName": {
                    "canRead": true,
                    "canEdit": true,
                    "value": "DisplayFirstName1692020045801"
                },
                "displayLastName": {
                    "canRead": true,
                    "canEdit": true,
                    "value": "DisplayLastName1692020045801"
                },
                "phone": {
                    "canRead": true,
                    "canEdit": true,
                    "value": "903-498-5014"
                },
                "timezone": {
                    "canRead": true,
                    "canEdit": true,
                    "value": {
                        "name": "Europe/Andorra",
                        "lat": 42.5,
                        "long": 1.5167,
                        "countries": [
                            {
                                "code": "AD",
                                "name": "Andorra",
                                "zones": [
                                    {
                                        "name": "Europe/Andorra",
                                        "lat": 42.5,
                                        "long": 1.5167,
                                        "countries": [
                                            {
                                                "code": "AD"
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                },
                "bio": {
                    "canRead": true,
                    "canEdit": true,
                    "value": "I'm Tester"
                },
                "status": {
                    "canRead": true,
                    "canEdit": true,
                    "value": "Active"
                },
                "roles": {
                    "canRead": true,
                    "canEdit": true,
                    "value": [
                        "Intern",
                        "Mentor",
                        "ExecutiveDevelopmentRepresentative",
                        "OfficeOfThePresident",
                        "ConsultantManager",
                        "Translator",
                        "LeadFinancialAnalyst",
                        "BibleTranslationLiaison",
                        "Consultant"
                    ]
                },

```

**Query and Input File**
[UpdateUserRoles.txt](https://github.com/SeedCompany/cord-api-v3/files/5231888/UpdateUserRoles.txt)

CordAPIV3# 6070e117

**Comment by CarsonF** [comment]
@iPiyushPatel can you post the error response here that's in your video? You say there's an error response, but the response you posted was successful.

I'm also seeing that the roles aren't being correctly updated. When you update the `roles` you are passing the complete list. GQL automatically converts your `roles: Controller` to `roles: [Controller]`. When you do that all the old roles should be deleted and replaced a with a list of a single item, Controller.

**Comment by iPiyushPatel** [comment]
Hi @CarsonF 

**GraphQL response**
```
{
    "errors": [
        {
            "message": "Invalid input ';': expected whitespace, UNIQUE or a pattern (line 2, column 7 (offset: 62))\r\n\"CREATE;\"\r\n       ^",
            "extensions": {
                "code": "InternalServerError",
                "status": 500,
                "codes": [
                    "InternalServerError"
                ],
                "exception": {
                    "message": "Invalid input ';': expected whitespace, UNIQUE or a pattern (line 2, column 7 (offset: 62))\r\n\"CREATE;\"\r\n       ^",
                    "stacktrace": [
                        "at Session.run (core\\database\\cypher.factory.ts:58:34)",
                        "at UserService.update (components\\user\\user.service.ts:519:10)",
                        "at UserResolver.updateUser (components\\user\\user.resolver.ts:173:18)"
                    ]
                }
            },
```
