### ISSUE TITLE
[BUG] Attempting to Terminate a Project throws errors.

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1476]
Attempted to change a Project that was 'Active' to 'Discussing Termination'.

Attempted to change another Project from 'Discussing Reactivation' to 'Discussing Termination'.

Received the following error for both.

```java
The project fQsZobuYiIf has never been in any of these previous steps: DiscussingReactivation, Suspended, Active, ActiveChangedPlan
  at ProjectRules.getMostRecentPreviousStep (components/project/project.rules.ts:874:13)
  at ProjectRules.getStepRule (components/project/project.rules.ts:627:19)
  at ProjectRules.getAvailableTransitions (components/project/project.rules.ts:743:40)
  at ProjectStepResolver.transitions (components/project/project-step.resolver.ts:25:12)
```

**Comment by sethmcknight** [comment]
Also while we're in here can we update this error message to use the Project Name instead of the Project ID?
