### ISSUE TITLE
Query error with users

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#515]
```
Neo4jError: Variable `userIds` not defined (line 5, column 7 (offset: 401))
"WHERE userIds.value CONTAINS $value2"
       ^
:
    at captureStacktrace (./node_modules/neo4j-driver/lib/v1/result.js:199:15)
    at new Result (./node_modules/neo4j-driver/lib/v1/result.js:65:19)
    at Session._run (./node_modules/neo4j-driver/lib/v1/session.js:152:14)
    at Session.run (./node_modules/neo4j-driver/lib/v1/session.js:130:19)
    at Session.run (./src/core/database/cypher.factory.ts:58:34)
    at Connection.run (./node_modules/cypher-query-builder/src/connection.ts:248:28)
    at Query.run (./node_modules/cypher-query-builder/src/query.ts:85:28)
    at DatabaseService.list (./src/core/database/database.service.ts:729:32)
    at OrganizationService.list (./src/components/organization/organization.service.ts:134:34)
    at UserService.listOrganizations (./src/components/user/user.service.ts:158:45)
```

**Comment by candleshine** [comment]
closed with PR #519 
switched to single UserId, instead of an array
