### ISSUE TITLE
Users (list) query fails when querying organizations within it

### ISSUE THREAD

**Issue by candleshine** [SeedCompany/cord-api-v3#544]
Sorry, I missed this thread until just now; I had responded on your issue.
The query that’s not working for me is users, not user. Here’s an example:
```
query users {
  items {
    email {
      value
    }
    fullName
    organizations {
      items {
        id
      }
    }
  }
}
```
Here’s the response:
```
{
  "errors": [
    {
      "message": "cannot read organization listDEBUG: {requestingUser, [object Object] target UserId -CFNGsmGF7}",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "response": {
            "statusCode": 401,
            "message": "cannot read organization listDEBUG: {requestingUser, [object Object] target UserId -CFNGsmGF7}",
            "error": "Unauthorized"
          },
          "status": 401,
          "message": "cannot read organization listDEBUG: {requestingUser, [object Object] target UserId -CFNGsmGF7}",
          "stacktrace": [
            "Error: cannot read organization listDEBUG: {requestingUser, [object Object] target UserId -CFNGsmGF7}",
            "    at UserService.listOrganizations (/Users/ryan/Coding/SeedCo/cord-api-v3/src/components/user/user.service.ts:223:13)",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      },
      "locations": [
        {
          "line": 8,
          "column": 7
        }
      ],
      "path": [
        "users",
        "items",
        0,
        "organizations"
      ]
    }
  ],
  "data": null
}
```
If I remove the organizations field from the query, the data returns

**Comment by candleshine** [comment]
Duplicate of #536
