### ISSUE TITLE
Cannot Create Multiple Projects with Same Name

### ISSUE THREAD

**Issue by glassblowerscat** [SeedCompany/cord-api-v3#917]
## Current Behavior
Cannot create more than one `Project` with the same name.

## Expected Behavior
Should be able to create multiple `Project`s with the same name

## Steps to Reproduce

1. Run the following mutation:

```
mutation {
  createProject (input: { project: { name: "TestProject1", type: Internship }}) {
    project {
      id
    }
  }
}
```
2. Note that the mutation returns a valid `id` for the new project
3. Run the same mutation again
4. Note that the mutation returns the following error:

```
[database:query] Duplicate property +4s { label: 'ProjectName', property: 'value', value: 'TestProject1' }

Neo4jError: Could not create project

    at captureStacktrace (node_modules/neo4j-driver/lib/v1/result.js:199:15)
    at new Result (node_modules/neo4j-driver/lib/v1/result.js:65:19)
    at Session._run (node_modules/neo4j-driver/lib/v1/session.js:152:14)
    at Session.run (node_modules/neo4j-driver/lib/v1/session.js:130:19)
    at Session.run (src/core/database/cypher.factory.ts:58:34)
    at Connection.run (node_modules/cypher-query-builder/src/connection.ts:248:28)
    at Query.run (node_modules/cypher-query-builder/src/query.ts:85:28)
    at Query.first (node_modules/cypher-query-builder/src/query.ts:160:17)
    at ProjectService.create (src/components/project/project.service.ts:339:42)
    at ProjectResolver.createProject (src/components/project/project.resolver.ts:139:47)
```
## Environment

| Tech      | Version / Name |
| --------- | -------------- |
| API       |       3c651949         |

**Comment by CarsonF** [comment]
Project names do need to be unique it's just that the error should be a `Duplicate` with the field `project.name` instead of a database error.
